services:
  app:
    image: fed_avg:latest
    user: "${UID}:${GID}"
  
  simulation:
    build: .
    image: fed_avg:latest
    container_name: fl
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [all]
    tty: true
    stdin_open: true