services:
  simulation:
    build: .
    image: fed_avg:latest
    container_name: fl
    user: "${UID}:${GID}"
    environment:
      - MPLCONFIGDIR=/tmp/matplotlib
      - HOME=/tmp
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [all]
    tty: true
    stdin_open: true